In [4]:
# Diagonal and Trace of a Matrix
import numpy as np

# 4x4 matrix of random integers
M = np.round( 5*np.random.randn(4,4)) # scaled up with *5 and rounded (just arbitrary)
print(M), print('')
d = np.diag(M)

# diag can be used differently depending on the input
d = np.diag(M) # output is vector
D = np.diag(d) # *if input is vector, output is matrix with the diagonals matching the input vector elements

print(d),print('')
print(D)


######## TRACE #############

tr = np.trace(M)
tr2 = sum( np.diag(M) )
print('')
print(tr,tr2)

[[  7.  -6.  11.   1.]
 [  2.   5.   1.  -5.]
 [  2.   5. -11.  -3.]
 [  6.  -1.  -5.  -4.]]

[  7.   5. -11.  -4.]

[[  7.   0.   0.   0.]
 [  0.   5.   0.   0.]
 [  0.   0. -11.   0.]
 [  0.   0.   0.  -4.]]

-3.0 -3.0
