In [7]:
######### MATRICES #############

import numpy as np


#### Contructing different types of Matrices ####

# square matrix
S = np.random.randn(5,5) # pass in rows and cols

# rectangular matrix
R = np.random.randn(5,2) # 5 rows, 2 cols

# Identity Matrix
I = np.eye(3) # just need single number for rows/cols - Identity matrix is always square

# zeros matrix
Z = np.zeros((4,4)) # first arg is size (use a tuple), second input is data type
# ex: complex type matrix with all 0s
CZ = np.zeros((4,4), dtype='complex')

# diagonal matrix
D = np.diag([1,2,3,4,5]) # pass in a list or numpy array and those numbers are used as the diagonal

# Triangular Matrix
# create a full matrix first
S = np.random.randn(5,5)
U = np.triu(S) # extract the upper triangular matrix
L = np.tril(S) # extract the lower triangular matrix

# Concatenate Matrices
A = np.random.randn(3,2)
B = np.random.randn(3,4) # rows must match
C = np.concatenate((A,B), axis=1)

[[-0.87585919  0.77849566 -1.1729058   0.94336384 -0.94574489 -1.11808526]
 [ 1.06576489 -1.48132181  0.97398098 -0.26239323  0.0817127   0.61200773]
 [-1.06486786  0.72942922  1.01294234  1.2620276  -1.27460921 -0.91406858]]
