In [4]:
### MATRIX ADDITION/SUBTRACTION

import numpy as np

A = np.random.randn(5,4)
B = np.random.randn(5,3)
C = np.random.randn(5,4)

# A+B # error: sizes do not match
A+C


######### SHIFTING A MATRIX #############

l = .3 # lambda scalar
N = 5 # size of a square matrix
D = np.random.randn(N,N) # can only shift a square matrix

Ds = D + l*np.eye(N)

print(D), print(' '), print(Ds)

# Note how the shifted matrix diagonals are changed, but not the other elements
  # Changing l (lambda) will only alter the diagonals by a small amount if you make lambda smaller



[[ 0.05006993  1.65539038  1.14496238 -1.22388126 -1.21320384]
 [ 0.43115535 -0.21174549 -0.79478907  1.05490888  0.60355636]
 [-0.4484203  -1.05623512 -0.97690861 -0.73237032  1.35415014]
 [-1.02727488  1.73488131 -0.30085992 -0.82697051  0.39808769]
 [ 0.70900938  0.07230839 -1.42018401  0.79363467 -0.56795722]]
 
[[ 0.35006993  1.65539038  1.14496238 -1.22388126 -1.21320384]
 [ 0.43115535  0.08825451 -0.79478907  1.05490888  0.60355636]
 [-0.4484203  -1.05623512 -0.67690861 -0.73237032  1.35415014]
 [-1.02727488  1.73488131 -0.30085992 -0.52697051  0.39808769]
 [ 0.70900938  0.07230839 -1.42018401  0.79363467 -0.26795722]]


(None, None, None)