In [3]:
########## MATRIX MULTIPLICATION ############
import numpy as np

#### Scalar Multiplication ####

M = np.array([ [1,2], [2,5] ])
s = 2

print(M*s) # [1*2, 2*2]  [2*2 2*5]
print(s*M)
# both results are the same since matrix scalar multiplication is commutative, element-wise

[[ 2  4]
 [ 4 10]]
[[ 2  4]
 [ 4 10]]


In [ ]:
# How Matrix Multiplication works

import numpy as np

A = np.array([[1, 2],
              [3,4],
              [5, 6]])

B = np.array([[7, 8],
             [9,10]])

# Multiply the row by each column in the other matrix. Each col in other matrix is an element in the row of the result matrix
# You have to go through all the columns on Matrix B per row of Matrix A to complete computation on one row of Matrix A (which makes a row of the product matrix)

# Let's calculate C11 (the first element of the result matrix) manually
C11 = (A[0,0] * B[0,0]) + (A[0,1] * B[1,0])
print(f"C11 = ({A[0,0]} * {B[0,0]}) + ({A[0,1]} * {B[1,0]}) = {C11}")

C12 = (A[0,0] * B[0,1]) + (A[0,1] * B[1,1])
print(f"C12 = ({A[0,0]} * {B[0,1]}) + ({A[0,1]} * {B[1,1]}) = {C12}")

# Now let's do the full matrix multiplication
C = A @ B
print("Full result:")
print(C)

# Matrix A must have same num cols m as Matrix B rows n -> n x m_col * m_col x m
# need to multiply each row in Matrix A by each col in Matrix B
  # each rowxcol -> one row element in result matrix
# once all cols in matrix B have been multiplied by, you're done with that row in the result matrix. Move to next row in Matrix A



In [4]:
### Matrix Multiplication is distributive and a linear operation ###

# matrix row and col sizes
m = 7
n = 5

A = np.random.randn(m,n)
B = np.random.randn(m,n)

# scalar
s = np.random.randn()

# Multiply scalar by the sum of Matrices A and B and the scalar by A and B separately
resL = s * (A+B)
resR = s*A + s*B 

print(resL)
print(resR)

# The two results should equal out to zero difference showing they are the same and this operation is distributive
print(resL - resR) # This is effectively a zero matrix. Due to rounding errors the numbers may be very small and close to zero

[[ 0.68223265  0.94874968 -0.38733081 -0.49969736  0.3090353 ]
 [-0.35851893  1.16488653 -0.45920293 -0.34630569  0.0981618 ]
 [ 0.24127935  0.21323068  0.05786893 -0.45568732 -0.15039676]
 [-0.10327487 -0.51592688  0.51179333 -0.04558114 -0.32110807]
 [-0.21271377  0.77220888 -0.3586892  -0.3393353   0.02604587]
 [-0.22747128 -0.8345488   0.19340661 -0.24540967  0.32134919]
 [-0.05154044  0.54420571 -0.70866694  0.81192237 -0.17072269]]
[[ 0.68223265  0.94874968 -0.38733081 -0.49969736  0.3090353 ]
 [-0.35851893  1.16488653 -0.45920293 -0.34630569  0.0981618 ]
 [ 0.24127935  0.21323068  0.05786893 -0.45568732 -0.15039676]
 [-0.10327487 -0.51592688  0.51179333 -0.04558114 -0.32110807]
 [-0.21271377  0.77220888 -0.3586892  -0.3393353   0.02604587]
 [-0.22747128 -0.8345488   0.19340661 -0.24540967  0.32134919]
 [-0.05154044  0.54420571 -0.70866694  0.81192237 -0.17072269]]
[[ 0.00000000e+00 -1.11022302e-16  0.00000000e+00  5.55111512e-17
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+