In [2]:
# Transposing Matrices
import numpy as np

M = np.array([ [1,2,3],
               [2,3,4] ])

print(M), print('')
print(M.T), print('') # transpose the matrix - .T only works on numpy arrays (not lists, etc.)
print(M.T.T), print('') # double transposed returns original

print(np.transpose(M)) # using transpose() method - works on non-numpy types like a multi-dimensional list while .T only works on numpy arrays

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]


In [13]:
# Warning with complex values in matrices
# The numpy transpose does not use hermetian transpose, just normal transpose

C = np.array([[3+2j, 3, 5-2j]])
print(C)
print('\n normal transpose (signs do not change):')
print(C.T)
print('')
print(np.transpose(C))
# we get the same signs for the complex imaginary component of the number 

print('\nHermitian Transpose (signs change):\n')
# Call Hermetian transpose explicitly
# First you need to compute the complex conjugate and then transpose - convert numpy array to matrix object, then call .H method for hermitian transposition
print(np.matrix(C).H) # see the sign flips on the imaginary parts (the signs of the real parts in the numbers stays the same)



[[3.+2.j 3.+0.j 5.-2.j]]

 normal transpose (signs do not change):
[[3.+2.j]
 [3.+0.j]
 [5.-2.j]]

[[3.+2.j]
 [3.+0.j]
 [5.-2.j]]

Hermitian Transpose (signs change):

[[3.-2.j]
 [3.-0.j]
 [5.+2.j]]
